//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Move()
        {
            
        }
    
        public int MoveId { get; set; }
        public string Move_name { get; set; }
        public string Description { get; set; }
        public string Types { get; set; }
        public Nullable<int> overallStat { get; set; }
    
        
    }
}
