//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pok
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Pokemon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemon()
        {
            this.Evolution = new HashSet<Evolution>();
            this.USES = new HashSet<USES>();
        }
    
        public int PokemonId { get; set; }
        public string Pokemon_name { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> Health { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> Attack { get; set; }
        public string Abilities { get; set; }
        public Nullable<decimal> Height_weight { get; set; }
        public Nullable<int> Level { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evolution> Evolution { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USES> USES { get; set; }
    }
}
