//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pok
{
    using System;
    using System.Collections.Generic;
    
    public partial class USES
    {
        public int Id { get; set; }
        public int TrainerId { get; set; }
        public int MoveId { get; set; }
        public int PokemonId { get; set; }
    
        public virtual Move Move { get; set; }
        public virtual Pokemon Pokemon { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
